### ISSUE TITLE
Memory leak when mouting files with a large amount of documents

### ISSUE THREAD

**Issue by nojhamster** [castorjs/castor-load#6]
Typical case : synchronizing a csv file with 100,000+ lines will greatly increase the memory consumption. I also suspect this to drastically slow the insertions/updates down.

I guess the middlewares are emitting documents too fast and a lot of operations have to be queued.

**Comment by kerphi** [comment]
Faudrait il envisager un système de gestion de la "back pressure" ?

**Comment by touv** [comment]
Le système existe sauf que visiblement middelware csv ne l'utilise pas contrairement au middleware xmlcorpus https://github.com/castorjs/castor-load-xmlcorpus/blob/master/index.js#L38

**Comment by touv** [comment]
le middleware jsoncorpus fonctionne de la même manière https://github.com/castorjs/castor-load-jsoncorpus/blob/master/index.js#L31

J'ai traité des fichiers  ~200000 docs sans constater de ralentissement...

**Comment by nojhamster** [comment]
Après de longues investigations, il est possible que les middlewares actuels ne gèrent pas très bien la backpressure. Du moins, le système que j'ai repris dans **jsoncorpus** ne fonctionne pas avec **csv** (je n'ai pas vérifié le comportement de jsoncorpus sur des grosses volumétries).
J'ai donc utilisé une autre méthode (https://github.com/castorjs/castor-load-csv/blob/master/index.js#L45).

La mémoire est maintenant stable pendant le chargement de gros fichiers csv, et le chargement des 230k docs d'ezpaarse est passé de 10m à 6m30s. (soit ~600/s)

J'essayerai de jeter un oeil aux autres middlewares pour vérifier que la backpressure est effectivement gérée correctement.

**Comment by pseudom** [comment]
Beau boulot !

**Comment by kerphi** [comment]
Oui, beau travail.
*18 additions* and *15 deletions*.
Comme quoi la qualité c'est pas la quantité !

2015-01-23 19:19 GMT+01:00 Dominique <notifications@github.com>:

> Beau boulot !

**Comment by nojhamster** [comment]
En testant le middleware **jsoncorpus**, je constate que la mémoire a également tendance à grimper, bien que ce soit beaucoup moins flagrant que pour le loader **csv**. Sur un "corpus" de **170k** documents, la consommation est passée progressivement de **170mb à 260mb**. En gérant la backpressure comme je l'ai fait dans le loader csv, la mémoire reste stable aux alentours de **185mb**, mais la vitesse d'insertion dans la base diminue beaucoup : **~170/sec** contre **~1000/sec** avant. (enfin, 1000/sec au début, car ça baisse progressivement)

Ce test m'a aussi permis de lever un autre lièvre, mais je vais mettre ça dans les issues de jsoncorpus. Je clos ce bug vu qu'il concerne les middlewares et non le coeur de castor-load.
