### ISSUE TITLE
Add a "getProperty" action

### ISSUE THREAD

**Issue by claussI** [castorjs/castor-load#9]
At the moment, there is no way to extract one element of an array / one property of an object.

Ex:

```json
{
  "set": [ "a", "b", "c" ],
  "getProperty": "0"
}
```

should return

````json
"a"
````

And 

```json
{
  "set": { "a": 0, "b": 1, "c":2 },
  "getProperty": "b"
}
```

should return

````json
1
````

**Comment by parmentf** [comment]
Oops. This issue is a castorjs/node-jbj one.
